import {R,S} from './init'

export const assoc = R["assoc"]
export const assocPath = R["assocPath"]
export const clone = R["clone"]
export const dissoc = R["dissoc"]
export const dissocPath = R["dissocPath"]
export const eqProps = R["eqProps"]
export const evolve = R["evolve"]
export const forEachObjIndexed = R["forEachObjIndexed"]
export const has = R["has"]
export const hasIn = R["hasIn"]
export const hasPath = R["hasPath"]
export const invert = R["invert"]
export const invertObj = R["invertObj"]
export const keys = R["keys"]
export const keysIn = R["keysIn"]
export const lens = R["lens"]
export const lensIndex = R["lensIndex"]
export const lensPath = R["lensPath"]
export const lensProp = R["lensProp"]
export const mapObjIndexed = R["mapObjIndexed"]
export const mergeDeepLeft = R["mergeDeepLeft"]
export const mergeDeepRight = R["mergeDeepRight"]
export const mergeDeepWith = R["mergeDeepWith"]
export const mergeDeepWithKey = R["mergeDeepWithKey"]
export const mergeLeft = R["mergeLeft"]
export const mergeRight = R["mergeRight"]
export const mergeWith = R["mergeWith"]
export const mergeWithKey = R["mergeWithKey"]
export const modify = R["modify"]
export const modifyPath = R["modifyPath"]
export const objOf = R["objOf"]
export const omit = R["omit"]
export const over = R["over"]
export const path = R["path"]
export const pathOr = R["pathOr"]
export const paths = R["paths"]
export const pick = R["pick"]
export const pickAll = R["pickAll"]
export const pickBy = R["pickBy"]
export const project = R["project"]
export const prop = R["prop"]
export const propOr = R["propOr"]
export const props = R["props"]
export const set = R["set"]
export const toPairs = R["toPairs"]
export const toPairsIn = R["toPairsIn"]
export const unwind = R["unwind"]
export const values = R["values"]
export const valuesIn = R["valuesIn"]
export const view = R["view"]
export const where = R["where"]
export const whereAny = R["whereAny"]
export const whereEq = R["whereEq"]
/* 
*
* */
export const renameKeys = R["renameKeys"]
export const mapKeys = R["mapKeys"]
export const renameKey =
  (a) => (b) => (o) => S.pipe(
    [ R.assoc(b)(o[a])
    , R.dissoc(a)
    ])(o)

