import {R,S} from './init'

export const clamp = R["clamp"]
export const countBy = R["countBy"]
export const difference = R["difference"]
export const differenceWith = R["differenceWith"]
export const eqBy = R["eqBy"]
export const equals = R["equals"]
export const gt = R["gt"]
export const gte = R["gte"]
export const identical = R["identical"]
export const innerJoin = R["innerJoin"]
export const intersection = R["intersection"]
export const lt = R["lt"]
export const lte = R["lte"]
export const max = R["max"]
export const maxBy = R["maxBy"]
export const min = R["min"]
export const minBy = R["minBy"]
export const pathEq = R["pathEq"]
export const propEq = R["propEq"]
export const sortBy = R["sortBy"]
export const sortWith = R["sortWith"]
export const symmetricDifference = R["symmetricDifference"]
export const symmetricDifferenceWith = R["symmetricDifferenceWith"]
export const union = R["union"]
export const unionWith = R["unionWith"]
